# coding: utf-8

"""
    My API

    A simple API for testing SDK generation

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from techcorp_api_client_dev.api.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()

    def tearDown(self) -> None:
        pass

    def test_messages_get(self) -> None:
        """Test case for messages_get

        Get messages
        """
        pass

    def test_messages_post(self) -> None:
        """Test case for messages_post

        Send message
        """
        pass

    def test_users_get(self) -> None:
        """Test case for users_get

        Get all users
        """
        pass

    def test_users_id_get(self) -> None:
        """Test case for users_id_get

        Get user by ID
        """
        pass

    def test_users_id_put(self) -> None:
        """Test case for users_id_put

        Update user
        """
        pass

    def test_users_post(self) -> None:
        """Test case for users_post

        Create a new user
        """
        pass


if __name__ == '__main__':
    unittest.main()
