# coding: utf-8

# flake8: noqa

"""
    My API

    A simple API for testing SDK generation

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# Define package exports
__all__ = [
    "DefaultApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "CreateUserRequest",
    "Message",
    "SendMessageRequest",
    "UpdateUserRequest",
    "User",
]

# import apis into sdk package
from my_api_client.api.default_api import DefaultApi as DefaultApi

# import ApiClient
from my_api_client.api_response import ApiResponse as ApiResponse
from my_api_client.api_client import ApiClient as ApiClient
from my_api_client.configuration import Configuration as Configuration
from my_api_client.exceptions import OpenApiException as OpenApiException
from my_api_client.exceptions import ApiTypeError as ApiTypeError
from my_api_client.exceptions import ApiValueError as ApiValueError
from my_api_client.exceptions import ApiKeyError as ApiKeyError
from my_api_client.exceptions import ApiAttributeError as ApiAttributeError
from my_api_client.exceptions import ApiException as ApiException

# import models into sdk package
from my_api_client.models.create_user_request import CreateUserRequest as CreateUserRequest
from my_api_client.models.message import Message as Message
from my_api_client.models.send_message_request import SendMessageRequest as SendMessageRequest
from my_api_client.models.update_user_request import UpdateUserRequest as UpdateUserRequest
from my_api_client.models.user import User as User
