# coding: utf-8

# flake8: noqa

"""
    My API

    A simple API for testing SDK generation

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "2.0.0-dev.20250709.1052"

# Define package exports
__all__ = [
    "DefaultApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "CreateUserRequest",
    "Message",
    "SendMessageRequest",
    "UpdateUserRequest",
    "User",
]

# import apis into sdk package
from techcorp_api_client_dev.api.default_api import DefaultApi as DefaultApi

# import ApiClient
from techcorp_api_client_dev.api_response import ApiResponse as ApiResponse
from techcorp_api_client_dev.api_client import ApiClient as ApiClient
from techcorp_api_client_dev.configuration import Configuration as Configuration
from techcorp_api_client_dev.exceptions import OpenApiException as OpenApiException
from techcorp_api_client_dev.exceptions import ApiTypeError as ApiTypeError
from techcorp_api_client_dev.exceptions import ApiValueError as ApiValueError
from techcorp_api_client_dev.exceptions import ApiKeyError as ApiKeyError
from techcorp_api_client_dev.exceptions import ApiAttributeError as ApiAttributeError
from techcorp_api_client_dev.exceptions import ApiException as ApiException

# import models into sdk package
from techcorp_api_client_dev.models.create_user_request import CreateUserRequest as CreateUserRequest
from techcorp_api_client_dev.models.message import Message as Message
from techcorp_api_client_dev.models.send_message_request import SendMessageRequest as SendMessageRequest
from techcorp_api_client_dev.models.update_user_request import UpdateUserRequest as UpdateUserRequest
from techcorp_api_client_dev.models.user import User as User
