/**
 * My API
 * A simple API for testing SDK generation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The SendMessageRequest model module.
 * @module model/SendMessageRequest
 * @version 2.0.0.20250709.1004
 */
class SendMessageRequest {
    /**
     * Constructs a new <code>SendMessageRequest</code>.
     * @alias module:model/SendMessageRequest
     * @param content {String} Message content
     * @param recipientId {Number} ID of the user who will receive the message
     */
    constructor(content, recipientId) { 
        
        SendMessageRequest.initialize(this, content, recipientId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, content, recipientId) { 
        obj['content'] = content;
        obj['recipient_id'] = recipientId;
    }

    /**
     * Constructs a <code>SendMessageRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SendMessageRequest} obj Optional instance to populate.
     * @return {module:model/SendMessageRequest} The populated <code>SendMessageRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SendMessageRequest();

            if (data.hasOwnProperty('content')) {
                obj['content'] = ApiClient.convertToType(data['content'], 'String');
            }
            if (data.hasOwnProperty('recipient_id')) {
                obj['recipient_id'] = ApiClient.convertToType(data['recipient_id'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>SendMessageRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>SendMessageRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of SendMessageRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['content'] && !(typeof data['content'] === 'string' || data['content'] instanceof String)) {
            throw new Error("Expected the field `content` to be a primitive type in the JSON string but got " + data['content']);
        }

        return true;
    }


}

SendMessageRequest.RequiredProperties = ["content", "recipient_id"];

/**
 * Message content
 * @member {String} content
 */
SendMessageRequest.prototype['content'] = undefined;

/**
 * ID of the user who will receive the message
 * @member {Number} recipient_id
 */
SendMessageRequest.prototype['recipient_id'] = undefined;






export default SendMessageRequest;

