/*
 * My API
 *
 * A simple API for testing SDK generation
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using TechCorp.ApiClient.Prod.Model;
using TechCorp.ApiClient.Prod.Client;
using System.Reflection;

namespace TechCorp.ApiClient.Prod.Test.Model
{
    /// <summary>
    ///  Class for testing SendMessageRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SendMessageRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SendMessageRequest
        //private SendMessageRequest instance;

        public SendMessageRequestTests()
        {
            // TODO uncomment below to create an instance of SendMessageRequest
            //instance = new SendMessageRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SendMessageRequest
        /// </summary>
        [Fact]
        public void SendMessageRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" SendMessageRequest
            //Assert.IsType<SendMessageRequest>(instance);
        }

        /// <summary>
        /// Test the property 'Content'
        /// </summary>
        [Fact]
        public void ContentTest()
        {
            // TODO unit test for the property 'Content'
        }

        /// <summary>
        /// Test the property 'RecipientId'
        /// </summary>
        [Fact]
        public void RecipientIdTest()
        {
            // TODO unit test for the property 'RecipientId'
        }
    }
}
