name: 'Setup SDK Generation Environment'
description: 'Sets up all required tools for SDK generation'
runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
      shell: bash
        
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
      shell: bash
        
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '11'
      shell: bash
        
    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'
      shell: bash
        
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0'
      shell: bash
        
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        tools: composer
      shell: bash
        
    - name: Install OpenAPI Generator
      run: npm install -g @openapitools/openapi-generator-cli
      shell: bash
