/*
 * My API
 *
 * A simple API for testing SDK generation
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Xunit;
using Microsoft.Extensions.DependencyInjection;
using TechCorp.ApiClient.Prod.Api;
using TechCorp.ApiClient.Prod.Model;


/* *********************************************************************************
*              Follow these manual steps to construct tests.
*              This file will not be overwritten.
*  *********************************************************************************
* 1. Navigate to ApiTests.Base.cs and ensure any tokens are being created correctly.
*    Take care not to commit credentials to any repository.
*
* 2. Mocking is coordinated by ApiTestsBase#AddApiHttpClients.
*    To mock the client, use the generic AddApiHttpClients.
*    To mock the server, change the client's BaseAddress.
*
* 3. Locate the test you want below
*      - remove the skip property from the Fact attribute
*      - set the value of any variables if necessary
*
* 4. Run the tests and ensure they work.
*
*/


namespace TechCorp.ApiClient.Prod.Test.Api
{
    /// <summary>
    ///  Class for testing DefaultApi
    /// </summary>
    public sealed class DefaultApiTests : ApiTestsBase
    {
        private readonly IDefaultApi _instance;

        public DefaultApiTests(): base(Array.Empty<string>())
        {
            _instance = _host.Services.GetRequiredService<IDefaultApi>();
        }

        /// <summary>
        /// Test MessagesGet
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task MessagesGetAsyncTest()
        {
            var response = await _instance.MessagesGetAsync();
            var model = response.Ok();
            Assert.IsType<List<Message>>(model);
        }

        /// <summary>
        /// Test MessagesPost
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task MessagesPostAsyncTest()
        {
            SendMessageRequest sendMessageRequest = default!;
            var response = await _instance.MessagesPostAsync(sendMessageRequest);
            var model = response.Created();
            Assert.IsType<Message>(model);
        }

        /// <summary>
        /// Test UsersGet
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task UsersGetAsyncTest()
        {
            var response = await _instance.UsersGetAsync();
            var model = response.Ok();
            Assert.IsType<List<User>>(model);
        }

        /// <summary>
        /// Test UsersIdGet
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task UsersIdGetAsyncTest()
        {
            int id = default!;
            var response = await _instance.UsersIdGetAsync(id);
            var model = response.Ok();
            Assert.IsType<User>(model);
        }

        /// <summary>
        /// Test UsersIdPut
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task UsersIdPutAsyncTest()
        {
            int id = default!;
            UpdateUserRequest updateUserRequest = default!;
            var response = await _instance.UsersIdPutAsync(id, updateUserRequest);
            var model = response.Ok();
            Assert.IsType<User>(model);
        }

        /// <summary>
        /// Test UsersPost
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task UsersPostAsyncTest()
        {
            CreateUserRequest createUserRequest = default!;
            var response = await _instance.UsersPostAsync(createUserRequest);
            var model = response.Created();
            Assert.IsType<User>(model);
        }
    }
}
