# coding: utf-8

# flake8: noqa
"""
    My API

    A simple API for testing SDK generation

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from my_api_client.models.create_user_request import CreateUserRequest
from my_api_client.models.message import Message
from my_api_client.models.send_message_request import SendMessageRequest
from my_api_client.models.update_user_request import UpdateUserRequest
from my_api_client.models.user import User
