# coding: utf-8

"""
    My API

    A simple API for testing SDK generation

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from techcorp_api_client_staging.models.create_user_request import CreateUserRequest

class TestCreateUserRequest(unittest.TestCase):
    """CreateUserRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateUserRequest:
        """Test CreateUserRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateUserRequest`
        """
        model = CreateUserRequest()
        if include_optional:
            return CreateUserRequest(
                name = '',
                email = ''
            )
        else:
            return CreateUserRequest(
                name = '',
                email = '',
        )
        """

    def testCreateUserRequest(self):
        """Test CreateUserRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
