/*
 * My API
 *
 * A simple API for testing SDK generation
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using TechCorp.ApiClient.Prod.Model;
using TechCorp.ApiClient.Prod.Client;
using System.Reflection;

namespace TechCorp.ApiClient.Prod.Test.Model
{
    /// <summary>
    ///  Class for testing UpdateUserRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UpdateUserRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for UpdateUserRequest
        //private UpdateUserRequest instance;

        public UpdateUserRequestTests()
        {
            // TODO uncomment below to create an instance of UpdateUserRequest
            //instance = new UpdateUserRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of UpdateUserRequest
        /// </summary>
        [Fact]
        public void UpdateUserRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" UpdateUserRequest
            //Assert.IsType<UpdateUserRequest>(instance);
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Fact]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }
    }
}
